[build]
  base = "ecommerce"  # Set the base directory for the React app
  publish = "ecommerce/dist"  # Vite build directory
  command = "npm run build"  # Build command

[context.production.environment]
  NODE_ENV = "production"
